# Generated by Django 3.2 on 2021-04-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
    ]
