# Generated by Django 3.2 on 2021-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Sem bio...', max_length=100, null=True),
        ),
    ]
