# Generated by Django 3.2 on 2021-06-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-profile__created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-profile__created_at']},
        ),
    ]
