# Generated by Django 3.2 on 2021-06-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210614_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-profile__id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-profile__id']},
        ),
    ]
