# Generated by Django 3.2 on 2021-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210716_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentskill',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
