# Generated by Django 3.2 on 2021-07-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_studentskill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentskill',
            options={'ordering': ['name']},
        ),
    ]
