# Generated by Django 3.2 on 2021-07-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_remove_university_is_active'),
        ('profiles', '0020_alter_studentskill_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSkill',
            new_name='Skill',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_attending_university',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='universities.major'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='universities.university'),
        ),
    ]
