# Generated by Django 3.2 on 2021-07-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_profile_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedIn',
        ),
    ]
