# Generated by Django 3.2 on 2021-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_mentor_expertise'),
        ('projects', '0003_project_mentors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='fields',
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Must be lowercase', max_length=50, null=True, unique=True)),
                ('mentors', models.ManyToManyField(related_name='markets', to='profiles.Mentor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='markets',
            field=models.ManyToManyField(related_name='projects', to='projects.Market'),
        ),
    ]
