# Generated by Django 3.2 on 2021-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_email'),
        ('projects', '0005_alter_market_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='markets', to='profiles.Mentor'),
        ),
    ]
