# Generated by Django 3.2 on 2021-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210417_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('startup', 'startup'), ('junior_enterprise', 'junior enterprise'), ('academic', 'academic project'), ('hobby', 'hobby')], max_length=50),
        ),
    ]
