# Generated by Django 3.2 on 2021-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210514_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
