# Generated by Django 3.2 on 2021-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default_project.jpeg', upload_to='projects_photos'),
        ),
    ]
