# Generated by Django 3.2 on 2021-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slogan',
            field=models.CharField(blank=True, help_text='Very quick description of the project', max_length=100, null=True),
        ),
    ]
