# Generated by Django 3.2 on 2021-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Detailed description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slogan',
            field=models.CharField(blank=True, help_text='Very quick description', max_length=100, null=True),
        ),
    ]
