# Generated by Django 3.2 on 2021-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210603_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(related_name='projects', to='projects.Link'),
        ),
    ]
