# Generated by Django 3.2 on 2021-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210609_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Link'),
        ),
    ]
