# Generated by Django 3.2 on 2021-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='Sem descrição...', help_text='Detailed description', max_length=1000),
        ),
    ]
