# Generated by Django 3.2 on 2021-06-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210614_1117'),
        ('projects', '0022_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnteringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_entering_requests', to='profiles.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entering_requests', to='projects.project')),
            ],
        ),
    ]
