# Generated by Django 3.2 on 2021-06-25 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
