# Generated by Django 3.2 on 2021-06-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210624_2335'),
        ('projects', '0026_auto_20210625_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('doubt', 'dúvida'), ('suggestion', 'sugestão'), ('feedback', 'feedback')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='profiles.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
