# Generated by Django 3.2 on 2021-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210627_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(blank=True, choices=[('doubt', 'dúvida'), ('suggestion', 'sugestão'), ('feedback', 'feedback')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
