# Generated by Django 3.2 on 2021-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_project_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
