# Generated by Django 3.2 on 2021-07-08 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210702_1503'),
        ('projects', '0036_discussionreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='visualized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_replies', to='profiles.profile'),
        ),
    ]
