# Generated by Django 3.2 on 2021-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20210708_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreply',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
