# Generated by Django 3.2 on 2021-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210709_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='body',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='content',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='{"blocks": [{"key": "5v3ub", "text": "Sem descrição...", "type": "unstyled", "depth": 0, "inlineStyleRanges": [], "entityRanges": [], "data": {}}], "entityMap": {}}', help_text='Detailed description', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default_project.jpg', null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Market'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slogan',
            field=models.CharField(default='', help_text='Very quick description', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='projectenteringrequest',
            name='message',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
