# Generated by Django 3.2 on 2021-07-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210709_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='body',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('startup', 'startup'), ('junior_enterprise', 'empresa júnior'), ('academic', 'projeto acadêmico'), ('social_project', 'projeto social')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default_project.jpg', upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectenteringrequest',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
