# Generated by Django 3.2 on 2021-07-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_projectstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='is_public',
        ),
    ]
