# Generated by Django 3.2 on 2021-07-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_remove_link_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('task_managers', 'gerenciadores de tarefas'), ('development_tools', 'ferramentas de desenvolvimento'), ('communication_channels', 'canais de comunicação')], max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('href', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Tool'),
        ),
    ]
