# Generated by Django 3.2 on 2021-07-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210720_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tools_categories',
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_categories', to='projects.project'),
        ),
    ]
