# Generated by Django 3.2 on 2021-07-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20210720_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project'),
        ),
    ]
