# Generated by Django 3.2 on 2021-07-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210725_2102'),
        ('projects', '0047_auto_20210720_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('member', 'membro')], max_length=50, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('invitation', 'invitation'), ('entry_request', 'entry_request')], max_length=50, null=True)),
                ('message', models.CharField(default='', max_length=500)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_requests', to='profiles.profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='projectenteringrequest',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='projectenteringrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pending_invited_mentors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pending_invited_students',
        ),
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='ProjectEnteringRequest',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Field'),
        ),
    ]
