# Generated by Django 3.2 on 2021-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210725_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='slogan',
            field=models.CharField(blank=True, help_text='Very quick description', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tool',
            name='href',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
