# Generated by Django 3.2 on 2021-07-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20210729_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('startup', 'startup'), ('academic', 'projeto acadêmico'), ('social_project', 'projeto social')], max_length=50, null=True),
        ),
    ]
