version: "3"
   
services:
  db:
    container_name: postgres-db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg_uniconn
      - POSTGRES_USER=uniconn
      - POSTGRES_PASSWORD=c*]C"7m;@P2Bkbg[t
  web:
    container_name: django-app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - db
volumes:
  postgres_data:
    driver: local