version: "3.9"
   
services:
  postgres-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg_uniconn
      - POSTGRES_USER=uniconn
      - POSTGRES_PASSWORD=c*]C"7m;@P2Bkbg[t
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - postgres-db
volumes:
  postgres_data:
    driver: local