# Generated by Django 3.2 on 2021-08-17 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_profile_options'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chats', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='visualized_by',
            field=models.ManyToManyField(blank=True, related_name='visualized_messages', to='profiles.Profile'),
        ),
    ]
