# Generated by Django 3.2 on 2021-04-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_mentor_expertise'),
        ('projects', '0004_auto_20210415_0841'),
        ('universities', '0003_alter_major_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='fields',
        ),
        migrations.DeleteModel(
            name='MajorField',
        ),
    ]
