# Generated by Django 3.2 on 2021-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_rename_cpnj_university_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
