# Generated by Django 3.2 on 2021-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_alter_major_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
