# Generated by Django 3.2 on 2021-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_alter_major_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
