# Generated by Django 3.2 on 2021-07-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_auto_20210709_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='cnpj',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
