# Generated by Django 3.2 on 2021-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0014_alter_major_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='cnpj',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
