# Generated by Django 3.2 on 2021-07-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0015_auto_20210709_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='cnpj',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
